name: Network CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        run: |
          python3.13 --version
          python3.13 -m pip --version

      - name: Create virtual environment
        run: |
          python3.13 -m venv .venv-ci
          .venv-ci/bin/python --version
          .venv-ci/bin/pip --version

      - name: Install dependencies
        run: |
          .venv-ci/bin/pip install -r requirements.txt

      - name: Check Batfish
        run: |
          docker ps
          curl -I http://localhost:9996 || true

      - name: Show files
        run: |
          pwd
          ls -R

      - name: Run tests
        run: |
          .venv-ci/bin/python -m pytest -v tests
